### ISSUE TITLE
i added the link for the tar file in my drive and got this error

### ISSUE THREAD

**Issue by isro01** [codebugged/avatar#3]
![demoerror](https://user-images.githubusercontent.com/25478966/84664086-a71f5080-af3b-11ea-88f0-b6249a0bffad.png)

**Comment by isro01** [comment]
plus the tar zip file seems to be empty

**Comment by codebugged** [comment]
Hi @isro01 
Actually it was under maintenance.
Hope it will work perfectly fine now, I have added the tar file

**Comment by isro01** [comment]
thanks works perfectly now!
