### ISSUE TITLE
ModuleNotFoundError: No module named 'demo'

### ISSUE THREAD

**Issue by rucha-deshmukh** [codebugged/avatar#4]
![Screenshot (117)](https://user-images.githubusercontent.com/42298890/84921736-804f4e80-b0e2-11ea-8693-d2df835c83b0.png)
Error for the last third command

**Comment by codebugged** [comment]
Hi @rucha0112 
Can you please send me ss

**Comment by codebugged** [comment]
@rucha0112 
You are not in the right drive. You shoud be inside avatar/the place where your video is

**Comment by rucha-deshmukh** [comment]
I am in the avatar drive

**Comment by codebugged** [comment]
Hi @rucha0112 
Can you please tell me where error was ?
