### ISSUE TITLE
While reading source image and video this error occurred

### ISSUE THREAD

**Issue by saidhury** [codebugged/avatar#6]
RuntimeError Traceback (most recent call last) /usr/local/lib/python3.6/dist-packages/imageio/plugins/ffmpeg.py in _read_frame_data(self) 620 raise RuntimeError( --> 621 "Frame is %i bytes, but expected %i." % (len(s), framesize) 622 ) RuntimeError: Frame is 0 bytes, but expected 248832. During handling of the above exception, another exception occurred: CannotReadFrameError Traceback (most recent call last) 

5 frames

/usr/local/lib/python3.6/dist-packages/imageio/plugins/ffmpeg.py in _read_frame_data(self) 626 err2 = self._stderr_catcher.get_text(0.4) 627 fmt = "Could not read frame %i:\n%s\n=== stderr ===\n%s" --> 628 raise CannotReadFrameError(fmt % (self._pos, err1, err2)) 629 return s, is_new 630 CannotReadFrameError: Could not read frame 7034: Frame is 0 bytes, but expected 248832. === stderr === ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers built with gcc 7 (Ubuntu 7.3.0-16ubuntu3) configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared libavutil 55. 78.100 / 55. 78.100 libavcodec 57.107.100 / 57.107.100 libavformat 57. 83.100 / 57. 83.100 libavdevice 57. 10.100 / 57. 10.100 libavfilter 6.107.100 / 6.107.100 libavresample 3. 7. 0 / 3. 7. 0 libswscale 4. 8.100 / 4. 8.100 libswresample 2. 9.100 / 2. 9.100 libpostproc 54. 7.100 / 54. 7.100 Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/content/drive/My Drive/data/avatar/my.mp4': Metadata: major_brand : isom minor_version : 512 compatible_brands: isomiso2avc1mp41 encoder : Lavf58.28.101 Duration: 00:03:54.66, start: 0.000000, bitrate: 243 kb/s Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 288x288 [SAR 1:1 DAR 1:1], 106 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default) Metadata: handler_name : VideoHandler Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default) Metadata: handler_name : SoundHandler Stream mapping: Stream #0:0 -> #0:0 (h264 (native) -> rawvideo (native)) Press [q] to stop, [?] for help Output #0, image2pipe, to 'pipe:': Metadata: major_brand : isom minor_version : 512 compatible_brands: isomiso2avc1mp41 encoder : Lavf57.83.100 Stream #0:0(und): Video: rawvideo (RGB[24] / 0x18424752), rgb24, 288x288 [SAR 1:1 DAR 1:1], q=2-31, 59719 kb/s, 30 fps, 30 tbn, 30 tbc (default) ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers built with gcc 7 (Ubuntu 7.3.0-16ubuntu3) configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared libavutil 55. 78.100 / 55. 78.100 libavcodec 57.107.100 / 57.107.100 libavformat 57. 83.100 / 57. 83.100 libavdevice 57. 10.100 / 57. 10.100 libavfilter 6.107.100 / 6.107.100 libavresample 3. 7. 0 / 3. 7. 0 libswscale 4. 8.100 / 4. 8.100 libswresample 2. 9.100 / 2. 9.100 libpostproc 54. 7.100 / 54. 7.100 Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/content/drive/My Drive/data/avatar/my.mp4': Metadata: major_brand : isom minor_version : 512 compatible_brands: isomiso2avc1mp41 encoder : Lavf58.28.101 Duration: 00:03:54.66, start: 0.000000, bitrate: 243 kb/s Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 288x288 [SAR 1:1 DAR 1:1], 106 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default) Metadata: handler_name : VideoHandler Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default) Metadata: handler_name : SoundHandler Stream mapping: Stream #0:0 -> #0:0 (h264 (native) -> rawvideo (native)) Press [q] to stop, [?] for help Output #0, image2pipe, to 'pipe:': Metadata: major_brand : isom minor_version : 512 compatible_brands: isomiso2avc1mp41 encoder : Lavf57.83.100 Stream #0:0(und): Video: rawvideo (RGB[24] / 0x18424752), rgb24, 288x288 [SAR 1:1 DAR 1:1], q=2-31, 59719 kb/s, 30 fps, 30 tbn, 30 tbc (default) Metadata: handler_name : VideoHandler encoder : Lavc57.107.100 rawvideo frame= 515 fps=0.0 q=-0.0 size= 125145kB time=00:00:17.16 bitrate=59719.7kbits/s speed=34.3x frame= 1173 fps=1172 q=-0.0 size= 285039kB time=00:00:39.10 bitrate=59719.7kbits/s speed=39.1x frame= 1821 fps=1213 q=-0.0 size= 442503kB time=00:01:00.70 bitrate=59719.7kbits/s speed=40.4x frame= 2419 fps=1208 q=-0.0 size= 587817kB time=00:01:20.63 bitrate=59719.7kbits/s speed=40.3x frame= 3063 fps=1224 q=-0.0 size= 744309kB time=00:01:42.10 bitrate=59719.7kbits/s speed=40.8x frame= 3654 fps=1217 q=-0.0 size= 887922kB time=00:02:01.80 bitrate=59719.7kbits/s speed=40.6x frame= 4200 fps=1199 q=-0.0 size= 1020600kB time=00:02:20.00 bitrate=59719.7kbits/s speed= 40x frame= 4734 fps=1182 q=-0.0 size= 1150362kB time=00:02:37.80 bitrate=59719.7kbits/s speed=39.4x frame= 5319 fps=1181 q=-0.0 size= 1292517kB time=00:02:57.30 bitrate=59719.7kbits/s speed=39.4x frame= 5896 fps=1178 q=-0.0 size= 1432728kB time=00:03:16.53 bitrate=59719.7kbits/s speed=39.3x frame= 6481 fps=1177 q=-0.0 size= 1574883kB time=00:03:36.03 bitrate=59719.7kbits/s speed=39.2x frame= 7035 fps=1176 q=-0.0 Lsize= 1709505kB time=00:03:54.50 bitrate=59719.7kbits/s speed=39.2x

**Comment by codebugged** [comment]
Compress the video
